### ISSUE TITLE
The pathToResources property is unused

### ISSUE THREAD

**Issue by dgabrielli76** [PolymerElements/app-localize-behavior#19] opened 2016-06-02 09:06 UTC
### Description

The `pathToResources` property is unused

### Expected outcome

The element use the path to load ressources from the behavior.

### Actual outcome

It seems that the property does not work.

_I will fix this and I will propose a PR to fix this issue._

**Comment by notwaldorf** [comment] 2016-08-29 17:28
Closing as duplicate of https://github.com/PolymerElements/app-localize-behavior/issues/33

**Comment by dgabrielli76** [comment] 2016-08-31 07:06
Due to the date of this issue, the duplicate should be the #33 not the #19, am I right?

**Comment by notwaldorf** [comment] 2016-09-06 21:08
@dgabrielli76 Sure, but I had already triaged that one, and changed its description to be more accurate, which is the only reason why I did this backwards. Also, oops, forgot to actually close it.

**Closed by notwaldorf** 2016-09-06 21:08 UTC
Labels: good-first-bug, help wanted, p1 - backlog
